#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VERSION="$(cat "$REPO_ROOT/VERSION")"
OUT_DIR="$REPO_ROOT/docs/generated"

mkdir -p "$OUT_DIR"

cat > "$OUT_DIR/inventory.md" <<EOF
# VeilKey Self-Hosted — Component Inventory

Product version: $VERSION

| Component | Path | README |
|-----------|------|--------|
| installer | \`installer/\` | \`installer/README.md\` |
| keycenter | \`services/keycenter/\` | \`services/keycenter/README.md\` |
| localvault | \`services/localvault/\` | \`services/localvault/README.md\` |
| proxy | \`services/proxy/\` | \`services/proxy/README.md\` |
| cli | \`client/cli/\` | \`client/cli/README.md\` |

## Supporting Paths

| Area | Path |
|------|------|
| docs | \`docs/\` |
| contracts | \`docs/cue/\` |
| hardcoding | \`docs/hardcoding/\` |
| tools | \`docs/tools/\` |
| facts | \`facts/\` |
| scripts | \`scripts/\` |

---
*Generated by docs/tools/generate.sh*
EOF

cat > "$OUT_DIR/terminology.md" <<EOF
# VeilKey Terminology

Canonical terms used across the self-hosted product surface.

| Term | Definition |
|------|------------|
| \`vault_node_uuid\` | Unique identifier assigned to each node running the localvault agent. |
| \`vault_hash\` | Stable content identity for a vault. |
| \`vault_runtime_hash\` | Hash reflecting the current runtime binding and integrity state. |
| \`keycenter\` | Central control-plane service for inventory, orchestration, and policy. |
| \`localvault\` | Node-local agent that stores ciphertext and reports runtime identity. |
| \`proxy\` | Outbound enforcement layer for operator and workload egress. |
| \`installer\` | Installation and verification layer for supported deployment profiles. |
| \`cli\` | Operator-facing command-line surface for the self-hosted deployment. |

---
*Generated by docs/tools/generate.sh*
EOF

echo "generate.sh: wrote $OUT_DIR/inventory.md"
echo "generate.sh: wrote $OUT_DIR/terminology.md"
