// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExecveProbe returns the embedded CollectionSpec for execveProbe.
func loadExecveProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecveProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load execveProbe: %w", err)
	}

	return spec, err
}

// loadExecveProbeObjects loads execveProbe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execveProbeObjects
//	*execveProbePrograms
//	*execveProbeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecveProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExecveProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execveProbeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveProbeSpecs struct {
	execveProbeProgramSpecs
	execveProbeMapSpecs
	execveProbeVariableSpecs
}

// execveProbeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveProbeProgramSpecs struct {
	TraceEnterExecve *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
}

// execveProbeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveProbeMapSpecs struct {
	ExecveEvents *ebpf.MapSpec `ebpf:"execve_events"`
}

// execveProbeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execveProbeVariableSpecs struct {
}

// execveProbeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecveProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveProbeObjects struct {
	execveProbePrograms
	execveProbeMaps
	execveProbeVariables
}

func (o *execveProbeObjects) Close() error {
	return _ExecveProbeClose(
		&o.execveProbePrograms,
		&o.execveProbeMaps,
	)
}

// execveProbeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecveProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveProbeMaps struct {
	ExecveEvents *ebpf.Map `ebpf:"execve_events"`
}

func (m *execveProbeMaps) Close() error {
	return _ExecveProbeClose(
		m.ExecveEvents,
	)
}

// execveProbeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecveProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveProbeVariables struct {
}

// execveProbePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecveProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type execveProbePrograms struct {
	TraceEnterExecve *ebpf.Program `ebpf:"trace_enter_execve"`
}

func (p *execveProbePrograms) Close() error {
	return _ExecveProbeClose(
		p.TraceEnterExecve,
	)
}

func _ExecveProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed execveprobe_bpfeb.o
var _ExecveProbeBytes []byte
